modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/DDX5/MCPaintball/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${mod_update_url}"
displayURL="${mod_display_url}"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
