modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="mcpaintball"
version="1.2.1-R"
displayName="MC Paintball"
authors="Multicoder"
description='''Minecraft paintball mod adds a vanilla way to paintball and have fun with friends.'''
[[dependencies.mcpaintball]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mcpaintball]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
